### ISSUE TITLE
cannot find the paper

### ISSUE THREAD

**Issue by FredHuang16** [michuanhaohao/AICITY2021_Track2_DMT#1]
Cannot find the paper 《An Empirical Study of Vehicle Re-Identification on the AI City Challenge》

Could you please provide the download link?

**Comment by michuanhaohao** [comment]
Hi!

Please check 'paper.pdf' in the repo.
![image](https://user-images.githubusercontent.com/23547900/118235048-c36a9b00-b4c6-11eb-8a7e-0c5e374f8df3.png)
