### ISSUE TITLE
RuntimeError: cannot perform reduction function min on tensor with no elements because the operation does not have an identity"

### ISSUE THREAD

**Issue by Zhanghao5200** [michuanhaohao/AICITY2021_Track2_DMT#10]
In the training process, there is always such an error:   

"File "/home/wit/DmtReid/loss/triplet_loss.py", line 102, in hard_example_mining
    dist_mat[is_neg].contiguous().view(N, -1), 1, keepdim=True)
RuntimeError: cannot perform reduction function min on tensor with no elements because the operation does not have an identity"

When I went to check the information printed on the terminal, I found that the number  of the query set and quelly set was 1,as follows

"=> AIC loaded
Dataset statistics:
  ----------------------------------------
  subset   | # ids | # images | # cameras
  ----------------------------------------
  train    |   440 |    52717 |        40
  query    |     1 |     1103 |        18
  gallery  |     1 |    31238 |        18
  ----------------------------------------"

At the same time, I print the relevant information of the error line ，as follows

"is_neg tensor:
([[False, False, False, False, False, False, False, False],
        [False, False, False, False, False, False, False, False],
        [False, False, False, False, False, False, False, False],
        [False, False, False, False, False, False, False, False],
        [False, False, False, False, False, False, False, False],
        [False, False, False, False, False, False, False, False],
        [False, False, False, False, False, False, False, False],
        [False, False, False, False, False, False, False, False]],
       device='cuda:0')
dist_mat:
tensor([[8.9935e-01, 1.3378e+01, 9.9388e+00, 1.2196e+01, 8.9468e+00, 1.1898e+01,
         1.3501e+01, 6.1112e+00],
        [1.3378e+01, 3.5938e-01, 1.2367e+01, 1.0789e+01, 1.2657e+01, 9.7843e+00,
         1.0603e+01, 1.2570e+01],
        [9.9388e+00, 1.2367e+01, 1.0000e-06, 1.1123e+01, 6.7836e+00, 1.2270e+01,
         1.2560e+01, 9.4772e+00],
        [1.2196e+01, 1.0789e+01, 1.1123e+01, 1.0000e-06, 1.0024e+01, 9.9253e+00,
         7.1910e+00, 1.1304e+01],
        [8.9468e+00, 1.2657e+01, 6.7836e+00, 1.0024e+01, 1.0000e-06, 1.1718e+01,
         1.1748e+01, 8.9490e+00],
        [1.1898e+01, 9.7843e+00, 1.2270e+01, 9.9253e+00, 1.1718e+01, 5.8055e-01,
         1.0002e+01, 1.0799e+01],
        [1.3501e+01, 1.0603e+01, 1.2560e+01, 7.1910e+00, 1.1748e+01, 1.0002e+01,
         4.8299e-01, 1.2935e+01],
        [6.1112e+00, 1.2570e+01, 9.4772e+00, 1.1304e+01, 8.9490e+00, 1.0799e+01,
         1.2935e+01, 1.0000e-06]], device='cuda:0', grad_fn=<SqrtBackward>)
dist_ap:
tensor([[13.5008],
        [13.3779],
        [12.5595],
        [12.1962],
        [12.6573],
        [12.2696],
        [13.5008],
        [12.9348]], device='cuda:0', grad_fn=<MaxBackward0>)"

I don't know where the problem is, can you help me ？

**Comment by michuanhaohao** [comment]
Solved via email.

**Comment by danielsyahputra** [comment]
@Zhanghao5200  @michuanhaohao Please, could you give me the solution to solve this problem?
