### ISSUE TITLE
 Cropped_dataset, and SPGAN_dataset.

### ISSUE THREAD

**Issue by leyuanxing** [michuanhaohao/AICITY2021_Track2_DMT#3]
Cropped_dataset, and SPGAN_dataset.的下载链接跳转不进去，可以提供一下其他下载方式吗？

**Comment by michuanhaohao** [comment]
你需要挂载VPN才能访问谷歌网盘，我们这里只能上传谷歌网盘，你方便找个有VPN的朋友帮忙下载一下吗？
