### ISSUE TITLE
 Cropped_dataset的实现代码

### ISSUE THREAD

**Issue by chenxiangzZ** [michuanhaohao/AICITY2021_Track2_DMT#5]
你好，有没有生成 Cropped_dataset的实现代码呢？

**Comment by michuanhaohao** [comment]
同学你好，我参考的是去年方案，你可以看这个repo呢

https://github.com/Xiangyu-CAS/AICity2020-VOC-ReID/issues/15

**Comment by chenxiangzZ** [comment]
这个利用heatmap显著图进行数据增强的手段能运用到person REID中么？

**Comment by michuanhaohao** [comment]
不一定，reid学术集的bbox已经框的很好，效果不一定能提升多少
