### ISSUE TITLE
pk采样和Loss

### ISSUE THREAD

**Issue by JunruChen-Image** [michuanhaohao/AICITY2021_Track2_DMT#6]
罗博士您好，我们最近复现了贵组的训练代码，确有一些问题和疑惑，希望您能帮忙指点一二，感谢！

1、分类Loss为什么没有采用带margin的cosface等，是和训练样本的id分布有关吗；
2、每个epoch的pk采样几乎遍历了全部图片，相比于遍历id每次随机采k张的采样方法，哪种方式更优呢，还是说对于不同的训练数据分布，可以选择不同的pk采样方式；
3、我们用单张v100训练点数确实很高，但换成多张2080Ti的DP训练，掉点比较明显，这个是因为syncBN的原因吗，但感觉掉点幅度偏大；
4、后处理中uda方法，对于mAP涨点幅度大吗，我们比赛时采用uda好像并不能涨太多点；

谢谢指教~

**Comment by michuanhaohao** [comment]
1、我们的工作中一直喜欢用原版的分类loss，我们把这个loss性能调的比较好，带margin的loss在我们这里效果都不如正常的分类loss。
2、遍历全部图片的性能会好一点点，除非遇到了极其长尾的数据集，后者的采样会更平衡一点。
3、多卡训练换成syBN会好一些，另外就是sampler也最好换成ddp的sampler
4、UDA的性能取决于伪标签的质量，我们融合了很多信息来提高伪标签的质量
