### ISSUE TITLE
requirements.txt has a number of unknown version dependencies

### ISSUE THREAD

**Issue by ccfarah** [michuanhaohao/AICITY2021_Track2_DMT#7]
The requirements.txt file has a number of packages that are pulled from a local drive, e.g.:
albumentations @ file:///home/conda/feedstock_root/build_artifacts/albumentations_1594363620148/work

Since I can't access these specific packages, I don't know the version or if any other modifications have been made to the package locally. As a result, attempting the installation with the most current version of each package, but this results in installation errors. Recommendations are appreciated.

**Comment by michuanhaohao** [comment]
You can delete this line and then try 'pip install albumentations'.

**Comment by ccfarah** [comment]
Thanks again for your help!

**Comment by ccfarah** [comment]
Hi Dr. Luo, this is what I did for the entire requirements file. My question was because I didn't know if there were local modifications made to the files that would impact simply installing the most current version.
