### ISSUE TITLE
train_label.xml not included

### ISSUE THREAD

**Issue by ccfarah** [michuanhaohao/AICITY2021_Track2_DMT#8]
I have the data directory set up, except for the xml file. Please assist/advise.

├── AIC21/
│   ├── AIC21_Track2_ReID/
│   	├── image_train/
│   	├── image_test/
│   	├── image_query/
│   	├── **train_label.xml**
│   	├── ...
│   	├── training_part_seg/
│   	    ├── cropped_patch/
│   	├── cropped_aic_test
│   	    ├── image_test/
│   	    ├── image_query/		
│   ├── AIC21_Track2_ReID_Simulation/
│   	├── sys_image_train/
│   	├── sys_image_train_tr/

**Comment by michuanhaohao** [comment]
Put xml files and other files into the data directory.

**Comment by ccfarah** [comment]
Hi Dr. Luo, thank you for your help. Just to be clear, I cannot find the train_label.xml file; else I would put it in the data directory, per the instructions.

Best,

Chris

**Comment by cfarah-anno** [comment]
Ignore this comment. I see that I have to request the original data from AICITY.

**Comment by korinl** [comment]
Hi. Is it possible to share some version of the .xml files . I just want to try to run the inference on my data. Thank you
