### ISSUE TITLE
RuntimeError: CUDA out of memory. Tried to allocate 108.00 MiB (GPU 0; 23.65 GiB total capacity; 22.40 GiB already allocated; 67.06 MiB free; 22.62 GiB reserved in total by PyTorch)

### ISSUE THREAD

**Issue by 1031kjy** [michuanhaohao/AICITY2021_Track2_DMT#9]
CUDA Out of Memory error but CUDA memory is almost empty

I currently want to train this model, but I have a runtime error.

- python train.py --config_file configs/stage1/resnext101a_384.yml MODEL.DEVICE_ID "('0')"

- RuntimeError: CUDA out of memory. Tried to allocate 108.00 MiB (GPU 0; 23.65 GiB total capacity; 22.40 GiB already allocated; 67.06 MiB free; 22.62 GiB reserved in total by PyTorch).

According to the message, I trained a model on small amount of data and changed the number of [CUDA_VISIBLE_DEVICES],  but I still have a runtime error.

Should I have more required space..? Any idea what might cause this ?

![image](https://user-images.githubusercontent.com/39287018/126322789-2e392dcd-8c97-4211-b0e7-e33ef3e59928.png)

**Comment by michuanhaohao** [comment]
The default training needs 32G GPU. You can try to reduce the batch size or train model with 256*128 image size.

**Comment by 1031kjy** [comment]
Hi Dr. Luo, Thank you for your help!!
